version: "3.3"

volumes:
  database-data: {}

networks:
  shield-network: {}

services:
  
  database:
    image: postgres:13.2-alpine
    ports:
      - 54320:5432
    environment:
      - POSTGRES_PASSWORD=avengerssecret
      - POSTGRES_USER=hawkeye
      - POSTGRES_DB=facebook-posts
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - shield-network

  restapi:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        PORT: 3000
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=ci
      - DB_PORT=${DB_PORT:-54320}
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - '3000:3000'
    networks:
      - shield-network
    
